services:
  - type: web
    name: zafarplaza-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app"
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 7936668543:AAEjYNdUk2fKNTa29mpnWdT9YBPx_E54hSg
      - key: ADMIN_CHAT_ID
        value: 8411892709
